[mqtt]
#ca_file = "ca.pem"
#key_file = "key.pem"
#cert_file = "cert.pem"
#keepalive_interval = 60
#topic_alias_max = 255

[[mqtt.brokers]]
host = "localhost"
port = 1883

## NOTE: Tunnel ID and MQTT topic are prepended to all IP packets
## Long IDs / topics will add significant overhead to traffic with many small packets

[server]
#id_length = 4
topic = "zika/OjFcZWEAGy2E3Vkh"
bind_cidr = "172.20.0.0/24"

[client]
bind_cidr = "172.20.0.0/24"

[[client.tunnels]]
#id_length = 4
topic = "zika/OjFcZWEAGy2E3Vkh"
bind_addr = "172.20.0.2"
